spring:
  datasource:
    #pass to db, in that case is a default pass
    url: 'jdbc:postgresql://localhost:5432/library_db'
    username: 'postgres'
    #that mean project took password from enviroment settings, or if he not found, he took 12345
    password: ${DB_PASSWORD:12345}
    #we say, what driver project must use(postgresql driver exactly)
    driver-class-name: org.postgresql.Driver
  jpa: #Java Persistence API
    #show sql requests in console logs
    show-sql: true
    hibernate:
      # validate: Checks if the Java Entity matches the Database Schema.
      # If the table is missing or columns are different -> Application STOP.
      # Unlike 'update', it NEVER modifies the database itself.
      ddl-auto: validate              #update
    properties:
      hibernate:
        #create sql logs more readable
        format_sql: true
        #dialect is like a language, with wich he can speak(PostgreSQl, MySQL,....)
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name:
      book_library
  profiles:
    active: dev

server:
  port: 1488

mvc:
  format:

    date: dd-MM-yyyy


